name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
    uses: docker/login-action@v1
    with: 
    registery: ghcr.io
    username: palee96
    password: ${{ secrets.TOKEN_FOR_GITHUB }}
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/palee96/nexofox-test:latest
        docker run ghcr.io/palee96/nexofox-test:latest
        docker push ghcr.io/palee96/nexofox-test:latest

