name: Docker Image CI

on: [push]

jobs:

  publish-docker-image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build docker image    
      run: |
        echo "${{ secrets.TOKEN_FOR_GITHUB }}" | docker login ghcr.io -u palee96 --password-stdin
        docker tag mycontainer ghcr.io/palee96/nexofox-test:latest
        docker push ghcr.io/palee96/nexofox-test:latest


